runtime: python
env: flex
entrypoint: gunicorn -b :$PORT BetterReads:app

runtime_config:
  python_version: 3

#need to redeploy to test : validating certs
env_variables:
   PYTHONHTTPSVERIFY: 1

skip_files:
- ^(node_modules/.*)
